name: 'Terraform Pull request'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCP_CREDENTIALS_PATH: "./gcp_credentials.json"
    steps:
      - name: 'Setting up job'
        run: |
          echo $GCP_CREDENTIALS > $GCP_CREDENTIALS_PATH
      - name: 'Checkout'
        uses: actions/checkout@master 

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './provisioning'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: $GCP_CREDENTIALS_PATH

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './provisioning'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: $GCP_CREDENTIALS_PATH

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './provisioning'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: $GCP_CREDENTIALS_PATH

      - name: 'Terraform Plan'
        id: 'terraform_plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './provisioning'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: $GCP_CREDENTIALS_PATH
